### PR TITLE
Don't segfault if getcell returns NULL.

### PR DESCRIPTION
**Pull request by kkuehlz**
This can happen in multithreaded contexts when the terminal resizes.
Instead of segfaulting, quit the function early. The library may
SIGABRT, which is much safer behavior.

### CODE REVIEW

**Comment by keur** [comment]
For context, this was discovered when using the library with [aerc](https://git.sr.ht/~sircmpwn/aerc). The library would segfault when the terminal would resize in a multithreaded environment. `aerc` only needed the NULL check in `erase_internal` and `putglyph`. I wasn't sure if that was necessary but I can wrap every call to `getcell` in a NULL check.

`putglyph` trace: https://i.fluffy.cc/1FqLd0zGzK6llfgn1xxf4BlcJ38rGJsp.html
`erase_internal` trace: https://i.fluffy.cc/dLz42pB2D0n50dhtZgDMFsl006c6J1df.html

**Comment by kkuehlz** [comment]
For context, this was discovered when using the library with [aerc](https://git.sr.ht/~sircmpwn/aerc). The library would segfault when the terminal would resize in a multi-threaded environment. `aerc` only needed the NULL check in `erase_internal` and `putglyph`. I wasn't sure if it is necessary, but I can wrap every call to `getcell` in a NULL check. Might be better to err on the safe side here since it is dangerous to have a library segfault.

`putglyph` trace: https://i.fluffy.cc/1FqLd0zGzK6llfgn1xxf4BlcJ38rGJsp.html
`erase_internal` trace: https://i.fluffy.cc/dLz42pB2D0n50dhtZgDMFsl006c6J1df.html

**Comment by justinmk** [comment]
cc @leonerd

**Comment by leonerd** [comment]
Yeah those changes seem reasonable, it's just adding a little defensiveness. It sortof sets a general precedent for trying to be more threadsafe, which is a slippery slope I don't want to begin right now, but if those fix a problem then sure. I'll apply the same patch upstream.

**Comment by kkuehlz** [comment]
@leonerd This causes the library to SIGABRT, so we solved the issue with locks. This patch was just meant to prevent segfaulting, so it doesn't specifically fix anything. If being thread-safe is not currently in scope for the library then not applying the patch is understandable. Up to you, and thanks for helping me debug on IRC.

**Pull request closed without merging**
